import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        // The PWA service worker (generated by scripts/build-sw.mjs). Never
        // let a CDN/browser cache it, or new deploys go unnoticed and the
        // "Update Now" banner never appears. The CSP limits what the worker
        // itself may load to our own origin.
        source: "/sw.js",
        headers: [
          { key: "Content-Type", value: "application/javascript; charset=utf-8" },
          { key: "Cache-Control", value: "no-cache, no-store, must-revalidate" },
          { key: "Content-Security-Policy", value: "default-src 'self'; script-src 'self'" },
        ],
      },
    ];
  },
};

export default nextConfig;
