// Stamps a unique build version into the service worker template and
// writes it to public/sw.js. Runs automatically before `npm run build`
// (the "prebuild" script). public/sw.js is generated, so it's gitignored.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, "src", "pwa", "sw.js");
const target = path.join(root, "public", "sw.js");

// Commit SHA (when available on Vercel) keeps versions traceable; the
// timestamp guarantees a new worker even for rebuilds of the same commit.
const sha = process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 7);
const version = [sha, Date.now().toString(36)].filter(Boolean).join("-");

const template = await readFile(source, "utf8");
if (!template.includes("__SW_VERSION__")) {
  throw new Error(`build-sw: __SW_VERSION__ placeholder missing from ${source}`);
}

const banner = "// GENERATED by scripts/build-sw.mjs from src/pwa/sw.js -- do not edit.\n";
await writeFile(target, banner + template.replaceAll("__SW_VERSION__", version));
console.log(`build-sw: wrote public/sw.js (version ${version})`);
